- hosts: all
  become: true
  tags:
    - always
  tasks:
    - name: Gather facts
      ansible.builtin.gather_facts:

- hosts: all
  become: true
  tags:
    - init
  roles:
    - common

- hosts: geth
  become: true
  tags:
    - geth
  roles:
    - rootchain-server

- hosts: fullnode:validator:non_validator
  become: true
  tags:
    - edge
  roles:
    - mounted-storage
    - edge

- hosts: fullnode:validator:non_validator
  become: true
  tags:
    - haproxy
  roles:
    - haproxy

- hosts: monitoring
  become: true
  tags:
    - monitoring
    - prometheus
  roles:
    - docker
    - prometheus

- hosts: all
  become: true
  tags:
    - monitoring
    - metric-exporters
  roles:
    - docker
    - metrics
